### ISSUE TITLE
"Pointer" abuse on buttons and labels

### ISSUE THREAD

**Issue by kittey** [r888888888/danbooru#1222]
Currently, buttons and labels use the pointer cursor (hand with digit extended) even though <a href="http://www.w3.org/TR/CSS21/ui.html#propdef-cursor">CSS 2.1</a> and <a href="http://www.w3.org/TR/2004/CR-css3-ui-20040511/#cursor0">CSS 3</a> state that pointers should only be used for links.

The <a href="http://msdn.microsoft.com/en-us/library/bb545459.aspx">Mouse and Pointer Guidelines</a> on the MSDN library have an interesting explanation on affordance and why buttons should not use the pointer cursor. Apple's <a href="http://developer.apple.com/library/mac/documentation/userexperience/conceptual/applehiguidelines/UEGuidelines/UEGuidelines.html#//apple_ref/doc/uid/TP40002720-SW4">Human Interface Guidelines</a> also expect the pointer cursor to only be used for links.

Labels have a low affordance (practically none), but that's fine because a user should not need to click a label. Clickable labels are useful next to checkboxes and radio buttons because they increase the otherwise tiny clickable area (see <a href="http://en.wikipedia.org/wiki/Fitts%27s_law">Fitts' law</a>), but the user doesn't need to know that the label is clickable. Using the pointer cursor on labels will make the user assume that the label is actually a link that leads elsewhere, which is incorrect.

Some of the occurrences in the Danbooru CSS:
```css
button,
input[type="button"],
input[type="reset"],
input[type="submit"] {
  cursor: pointer;
  -webkit-appearance: button; }

div#page aside#sidebar > section#blacklist-box ul a {
    color: #0073ff;
    cursor: pointer; }

form.simple_form div.input label {
    display: block;
    cursor: pointer;
    font-weight: bold;
    line-height: 1.5em; }

div#c-pool-orders div#a-edit ul.ui-sortable li {
    cursor: pointer;
    /* ... */ }
```
There are other occurrences, but I don't know where those styles are used.

I believe using the pointer cursor for notes is justified because there's no other indication that the tooltip needs to be clicked to edit the note (i.e. zero affordance). Doesn't apply to the note edit window's buttons, which should not have pointer cursors.

I know that some other sites abuse the pointer cursor too, but that doesn't really justify doing the same. GitHub, for example, doesn't even use it consistently: The "Submit new issue" button has the pointer cursor while the "New Issue" button in the top right has the default arrow... while writing a new issue. Otherwise, the "New Issue" button also has the pointer. :-S
