### ISSUE TITLE
Add more IDs to side menu elements

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#4167]
This idea was brought up from a request of [DeusExCalamus](/users/75306) on Discord, where it was asked if the original position of the menu items could be restored from how they were changed in 5729d92c8ecdcd7ce313d2772712cc3a4143a639. This was somewhat possible with the following CSS (taken and altered from [forum #139704](https://danbooru.donmai.us/forum_posts/139704)).

```css
#c-posts #a-show #post-options ul { display: flex; flex-direction: column; }
#c-posts #a-show #post-options li:nth-child(1)  { order: 1; } /* resize */
#c-posts #a-show #post-options li:nth-child(4)  { order: 2; } /* favorite */
#c-posts #a-show #post-options li:nth-child(5)  { order: 3; } /* unfavorite */
#c-posts #a-show #post-options li:nth-child(6) { order: 4; } /* edit */
#c-posts #a-show #post-options li:nth-child(3) { order: 5; } /* download */
#c-posts #a-show #post-options li:nth-child(7) { order: 6; } /* pool */
#c-posts #a-show #post-options li:nth-child(8) { order: 7; } /* note */
#c-posts #a-show #post-options li:nth-child(9)  { order: 8; } /* commentary */
#c-posts #a-show #post-options li:nth-child(10) { order: 9; } /* favgroup */
#c-posts #a-show #post-options li:nth-child(2) { order: 10; } /* similar */
#c-posts #a-show #post-options li:nth-child(11) { order: 11; } /* flag */
#c-posts #a-show #post-options li:nth-child(12) { order: 12; } /* other1 */
#c-posts #a-show #post-options li:nth-child(13) { order: 13; } /* other2 */
```

However it wasn't optimal as it only fully works if all of the options are static, however the number of options can vary from page to page, for instance "Copy notes" will only appear on pages with notes. So I looked into the viability of using IDs on elements to overcome that shortcoming with the following userscript.

https://gist.github.com/BrokenEagle/325dad8a62dedb0a36fab7be04fff728

It works as expected, as the menu items appear in their intended order regardless of which option is present. Therefore if IDs are added to all of the side menu items on the post show menu, to include the **Information**, **Options**, and **History** sections, then with CSS users can change the order to their own desire. Additionally, they could hide menu items they don't wish to see, or perhaps enhance them in some way.

The only post index section of note is **Related**, so that one could be done as well.
